export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_FAIL = 'SEND_CONTACT_FAIL';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SESSION_SUCCESS = 'SESSION_SUCCESS';
export const SESSION_FAIL = 'SESSION_FAIL';
export const CLEAR_SESSION = 'CLEAR_SESSION';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAIL = 'ORDER_FAIL';

export const MUSICIAN_ADD_SUCCESS = 'MUSICIAN_ADD_SUCCESS';
export const MUSICIAN_ADD_FAIL = 'MUSICIAN_ADD_FAIL';
export const SET_MUSICIAN_LOADING = 'SET_MUSICIAN_LOADING';
export const INSTRUMENT_SENT = 'INSTRUMENT_SENT';
export const INSTRUMENT_FAIL = 'INSTRUMENT_FAIL';
export const SET_INSTRUMENT_LOADING = 'SET_INSTRUMENT_LOADING';

export const VOLUNTEER_ADD_SUCCESS = 'VOLUNTEER_ADD_SUCCESS';
export const VOLUNTEER_ADD_FAIL = 'VOLUNTEER_ADD_FAIL';
export const SET_VOLUNTEER_LOADING = 'SET_VOLUNTEER_LOADING';
export const CLEAR_ADD_VOLUNTEER = 'CLEAR_ADD_VOLUNTEER';

export const NEEDS_ADD_SUCCESS = 'NEEDS_ADD_SUCCESS';
export const NEEDS_ADD_FAIL = 'NEEDS_ADD_FAIL';
export const SET_NEEDS_LOADING = 'SET_NEEDS_LOADING';
export const CLEAR_ADD_NEEDS = 'CLEAR_ADD_NEEDS';
